# Generated by Django 5.0.6 on 2024-05-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_video',
            old_name='URL',
            new_name='Video_URL',
        ),
        migrations.RemoveField(
            model_name='training_video',
            name='Aspect',
        ),
        migrations.RemoveField(
            model_name='training_video',
            name='Tools_ID01',
        ),
    ]
