# Generated by Django 5.0.6 on 2024-05-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_url_training_video_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_video',
            name='Video_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
