# Generated by Django 5.0.6 on 2024-05-30 02:47

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_training_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_video',
            name='Video_URL',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
