# Generated by Django 5.0.6 on 2024-05-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_training_video_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tools',
            options={'ordering': ['-tool_id']},
        ),
        migrations.AlterModelOptions(
            name='training_video',
            options={'ordering': ['-Video_id']},
        ),
        migrations.AlterField(
            model_name='training_video',
            name='descriptions',
            field=models.CharField(max_length=2000),
        ),
    ]
