# Generated by Django 5.0.6 on 2024-06-06 08:36

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_tools_options_alter_training_video_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='name',
            field=models.CharField(max_length=100, validators=[dashboard.models.validate_unique_name]),
        ),
    ]
