# Generated by Django 5.0.4 on 2024-05-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tools_training_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_video',
            name='Aspect',
            field=models.CharField(max_length=100),
        ),
    ]
