# Generated by Django 5.0.4 on 2024-05-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_training_video_aspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_video',
            name='pdf_field',
            field=models.FileField(default='pdfs/default.pdf', upload_to='pdfs/'),
        ),
    ]
